name       : xrdp
version    : 0.9.1
release    : 6
source     :
    - git|https://github.com/neutrinolabs/xrdp.git : 2f382d2a16b3d6ec571f408567c7a3f49b4b628a
license    : GPL-2.0
component  : network.util
summary    : xRDP Server
description: |
    An open source remote desktop protocol (RDP) server
builddeps  :
    - libjpeg-turbo-devel
    - pkgconfig(libpulse)
    - pkgconfig(fuse)
    - pkgconfig(xrandr)
    - pkgconfig(x11)
    - pkgconfig(xfixes)
setup      : |
    %reconfigure --with-systemdsystemunitdir=/usr/lib/systemd/system \
               --enable-jpeg \
               --enable-simplesound \
               --enable-fuse \
               --enable-loadpulsemodules
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
    rm $installdir/%libdir%/**/*.a
