name       : xrdp
version    : 0.9.5
release    : 8
source     :
    - https://github.com/neutrinolabs/xrdp/releases/download/v0.9.5/xrdp-0.9.5.tar.gz : 0c66b06204237745be3f0a75bfdd22a2b27de97740490256964bb5082efb0042
license    : GPL-2.0
component  : network.util
summary    : xRDP Server
description: |
    An open source remote desktop protocol (RDP) server
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libturbojpeg)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
    - pkgconfig(x11)
setup      : |
    %configure --with-systemdsystemunitdir=/usr/lib/systemd/system \
               --enable-jpeg \
               --enable-fuse
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
    rm $installdir/%libdir%/**/*.a
