name       : xrdp
version    : 0.9.1
release    : 5
source     :
    - https://github.com/neutrinolabs/xrdp/releases/download/v0.9.1/xrdp-0.9.1.tar.gz : bb07ae1150b86b0186059d4485a458a39e14e89b127ca29ea9f24484ff746bdd
license    : GPL-2.0
component  : network.util
summary    : xRDP Server
description: |
    An open source remote desktop protocol (RDP) server
builddeps  :
    - libjpeg-turbo-devel
    - pkgconfig(libpulse)
    - pkgconfig(fuse)
    - pkgconfig(xrandr)
    - pkgconfig(x11)
    - pkgconfig(xfixes)
setup      : |
    ./bootstrap
    %configure --with-systemdsystemunitdir=/usr/lib/systemd/system \
               --enable-jpeg \
               --enable-simplesound \
               --enable-fuse \
               --enable-loadpulsemodules \
               --disable-static
build      : |
    %make
install    : |
    %make_install
