name       : xrdp
version    : 0.9.9
release    : 13
source     :
    - https://github.com/neutrinolabs/xrdp/releases/download/v0.9.9/xrdp-0.9.9.tar.gz : 8edf33346a8b3718a828d2c998ac1a036ea707e7f02b47092c8ae20dd71a9362
license    : Apache-2.0
component  : network.util
summary    : xRDP Server
description: |
    An open source remote desktop protocol (RDP) server
builddeps  :
    - pkgconfig(fdk-aac)
    - pkgconfig(fuse)
    - pkgconfig(libturbojpeg)
    - pkgconfig(opus)
    - pkgconfig(pixman-1)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
setup      : |
    %configure \
        --with-systemdsystemunitdir=%libdir%/systemd/system \
        --enable-fdkaac \
        --enable-fuse \
        --enable-ipv6 \
        --enable-jpeg \
        --enable-opus \
        --enable-pixman \
        --enable-tjpeg
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
    rm $installdir/%libdir%/**/*.a

    rm $installdir/etc/xrdp/startwm.sh

    sed -i 's/system-auth/login/g' $installdir/etc/pam.d/xrdp-sesman

    # TODO keep file in /etc, it isn't recognized in /usr/share/defaults/etc..
    install -Dm00644 $installdir/etc/pam.d/xrdp-sesman $installdir/usr/share/defaults/etc/pam.d/xrdp-sesman
