name       : xrdp
version    : 0.9.4
release    : 7
source     :
    - https://github.com/neutrinolabs/xrdp/releases/download/v0.9.4/xrdp-0.9.4.tar.gz : 059e362db550b58a108117e6538363d90f07edd0a54810affae977a6b0bb6ea7
license    : GPL-2.0
component  : network.util
summary    : xRDP Server
description: |
    An open source remote desktop protocol (RDP) server
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
    - pkgconfig(x11)
    - libjpeg-turbo-devel
setup      : |
    %configure --with-systemdsystemunitdir=/usr/lib/systemd/system \
               --enable-jpeg \
               --enable-fuse
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
    rm $installdir/%libdir%/**/*.a
