name       : xrdp
version    : 0.9.21
release    : 20
source     :
    - https://github.com/neutrinolabs/xrdp/releases/download/v0.9.21/xrdp-0.9.21.tar.gz : aae7f1a725bf92a327276de4f77469a5540456c934bbe8a44da67d4974193fb8
homepage   : http://xrdp.org/
license    : Apache-2.0
component  : network.util
summary    : An open-source Remote Desktop Protocol server
description: |
    xrdp provides a graphical login to remote machines using RDP (Microsoft Remote Desktop Protocol). xrdp accepts connections from variety of RDP clients: FreeRDP, rdesktop, NeutrinoRDP and Microsoft Remote Desktop Client (for Windows, macOS, iOS and Android).
builddeps  :
    - pkgconfig(fdk-aac)
    - pkgconfig(fuse)
    - pkgconfig(libturbojpeg)
    - pkgconfig(opus)
    - pkgconfig(pixman-1)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
setup      : |
    %configure \
        --with-systemdsystemunitdir=%libdir%/systemd/system \
        --enable-fdkaac \
        --enable-fuse \
        --enable-ipv6 \
        --enable-jpeg \
        --enable-opus \
        --enable-pixman \
        --enable-tjpeg
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
    rm $installdir/%libdir%/**/*.a

    rm $installdir/etc/xrdp/startwm.sh

    sed -i 's/system-auth/login/g' $installdir/etc/pam.d/xrdp-sesman

    # TODO keep file in /etc, it isn't recognized in /usr/share/defaults/etc..
    install -Dm00644 $installdir/etc/pam.d/xrdp-sesman $installdir/usr/share/defaults/etc/pam.d/xrdp-sesman
