name       : xrdp
version    : 0.8.0
release    : 3
source     :
    - https://github.com/neutrinolabs/xrdp/archive/v0.8.0.tar.gz : 555f78980a3100d5bc8ea7cc6e3c49dd32dbeae9b686d90dd4e21d2c93a0d422
license    : GPL-2.0
summary    : xRDP Server
description: |
    An open source remote desktop protocol (RDP) server
builddeps  :
    - libjpeg-turbo-devel
    - pkgconfig(libpulse)
    - pkgconfig(fuse)
    - pkgconfig(xrandr)
    - pkgconfig(x11)
    - pkgconfig(xfixes)
setup      : |
    ./bootstrap
    %configure --with-systemdsystemunitdir=/usr/lib/systemd/system \
               --enable-jpeg \
               --enable-simplesound \
               --enable-fuse \
               --enable-loadpulsemodules
build      : |
    %make
install    : |
    %make_install
