name       : xrdp
version    : 0.9.8
release    : 9
source     :
    - https://github.com/neutrinolabs/xrdp/releases/download/v0.9.8/xrdp-0.9.8.tar.gz : bbb2c114903d65c212cb2cca0b11bb2620e5034fa9353e0479bc8aa9290b78ee
license    : Apache-2.0
component  : network.util
summary    : xRDP Server
description: |
    An open source remote desktop protocol (RDP) server
builddeps  :
    - pkgconfig(fdk-aac)
    - pkgconfig(fuse)
    - pkgconfig(libturbojpeg)
    - pkgconfig(opus)
    - pkgconfig(pixman-1)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
setup      : |
    %configure \
        --with-systemdsystemunitdir=%libdir%/systemd/system \
        --enable-fdkaac \
        --enable-fuse \
        --enable-ipv6 \
        --enable-jpeg \
        --enable-opus \
        --enable-pixman \
        --enable-tjpeg
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
    rm $installdir/%libdir%/**/*.a
