name       : xrdp
version    : 0.6.1
release    : 2
source     :
    - https://github.com/neutrinolabs/xrdp/archive/v0.6.1.tar.gz : 7b5a91fc5aa5a36bebff2b5ed19854486bf8836b7d01ad7bb00caa4e6b107c5b
license    : GPL-2.0
summary    : xRDP Server
description: |
    An open source remote desktop protocol (RDP) server
builddeps  :
    - libjpeg-turbo-devel
    - pkgconfig(libpulse)
    - pkgconfig(fuse)
    - pkgconfig(xrandr)
    - pkgconfig(x11)
    - pkgconfig(xfixes)
setup      : |
    ./bootstrap
    %configure --with-systemdsystemunitdir=/usr/lib/systemd/system \
               --enable-jpeg \
               --enable-simplesound \
               --enable-fuse \
               --enable-loadpulsemodules
build      : |
    %make
install    : |
    %make_install
